export const DESIGNE_LAUNCH_WIDTH = 600;
export const DESIGNE_LAUNCH_HEIGHT = 300;
export const DESIGNE_DASHBOARD_WIDTH = 800;
export const DESIGNE_DASHBOARD_HEIGHT = 750;

export const BASE_WIN_WIDTH = 1920;
export const BASE_WIN_HEIGHT = 1080;
